import { randomBytes, randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify'; import type { GameType } from './shared/types.js'; import { config, supportedGames } from './config.js'; import { RoomService } from './rooms.js'; import { page } from './ui/page.js';
const parse = <T>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const access = (request: { headers: Record<string, unknown>; query: unknown }) => String((request.headers['x-room-access'] as string | undefined) ?? (request.query as { accessToken?: string }).accessToken ?? '');
export function registerHttp(app: FastifyInstance, rooms: RoomService) {
  const adminTokens = new Map<string, number>();
  const admin = (request: { headers: Record<string, unknown> }) => { const token = request.headers['x-admin-token']; const expires = typeof token === 'string' ? adminTokens.get(token) : undefined; return Boolean(expires && expires > Date.now()); };
  app.post('/api/admin/login', async (request, reply) => { if (!config.adminPassword) return reply.code(503).send({ error: '尚未設定 ADMIN_PASSWORD' }); if ((request.body as { password?: string }).password !== config.adminPassword) return reply.code(401).send({ error: '管理者密碼錯誤' }); const token = randomBytes(24).toString('base64url'); adminTokens.set(token, Date.now() + 8 * 60 * 60_000); return { token, expiresAt: Date.now() + 8 * 60 * 60_000 }; });
  app.get('/api/admin/rooms', async (request, reply) => { if (!admin(request)) return reply.code(401).send({ error: '需要管理者登入' }); return { rooms: rooms.listAll() }; });
  app.delete('/api/admin/rooms/:id', async (request, reply) => { if (!admin(request)) return reply.code(401).send({ error: '需要管理者登入' }); const id = (request.params as { id: string }).id; if (!rooms.getStored(id)) return reply.code(404).send({ error: '房間不存在' }); rooms.delete(id); return { ok: true }; });
  app.post('/api/admin/rooms/bulk-delete', async (request, reply) => { if (!admin(request)) return reply.code(401).send({ error: '需要管理者登入' }); const ids = [...new Set((request.body as { ids?: unknown }).ids instanceof Array ? (request.body as { ids: unknown[] }).ids.filter((id): id is string => typeof id === 'string' && /^[a-z0-9]{6,64}$/i.test(id)).slice(0, 200) : [])]; if (!ids.length) return reply.code(400).send({ error: '請選擇至少一個房間' }); for (const id of ids) if (rooms.getStored(id)) rooms.delete(id); return { ok: true, deleted: ids.length }; });
  app.get('/api/rooms/:id', async (request, reply) => { const id = (request.params as { id: string }).id; const stored = rooms.getStored(id); if (!stored) return reply.code(404).send({ error: '房間不存在' }); if (!rooms.canAccess(id, access(request))) return reply.code(403).send({ error: '此房間需要驗證密碼', game: stored.game }); const room = rooms.rooms.get(id); if (room) return rooms.snapshot(room); return { id: stored.id, game: stored.game, status: stored.status, config: parse(stored.config, {}), state: parse(stored.final_state, {}), persisted: true }; });
  app.post('/api/rooms', async (request, reply) => { const body = request.body as { game: GameType; name: string; password?: string; config?: Record<string, unknown> }; if (!supportedGames.includes(body.game) || !body.name?.trim()) return reply.code(400).send({ error: '設定不完整' }); const result = rooms.create(body.game, body.name, body.config ?? {}, body.password); return reply.code(201).send({ roomId: result.room.id, hostId: result.hostId, reconnectToken: result.reconnectToken, accessToken: result.accessToken, url: `/rooms/${result.room.id}` }); });
  app.post('/api/rooms/:id/verify', async (request, reply) => { const value = rooms.verifyPassword((request.params as { id: string }).id, (request.body as { password?: string }).password); if (value === undefined) return reply.code(404).send({ error: '房間不存在' }); if (value === null) return reply.code(401).send({ error: '密碼錯誤' }); return { accessToken: value }; });
  app.get('/api/history', async request => { const ids = ((request.query as { localIds?: string }).localIds ?? '').split(',').filter(id => /^[a-z0-9]{6,32}$/i.test(id)).slice(0, 100); return rooms.history(ids).map(row => ({ id: row.id, game: row.game, status: row.status, createdAt: row.created_at, finishedAt: row.finished_at, result: parse(row.result, null) })); });
  app.get('/api/results/:id', async (request, reply) => { const id = (request.params as { id: string }).id; const stored = rooms.getStored(id); if (!stored) return reply.code(404).send({ error: '結果不存在' }); if (!rooms.canAccess(id, access(request))) return reply.code(403).send({ error: '此結果需要驗證密碼' }); return { id, game: stored.game, status: stored.status, config: parse(stored.config, {}), result: parse(stored.result, null), finalState: parse(stored.final_state, {}), finishedAt: stored.finished_at, events: rooms.events(id), messages: rooms.roomMessages(id).slice(-20) }; });
  app.post('/api/templates', async (request, reply) => { const body = request.body as { game: GameType; config: Record<string, unknown>; share?: boolean }; if (!supportedGames.includes(body.game) || !body.config) return reply.code(400).send({ error: '模板設定不完整' }); const id = randomUUID(); const shareCode = body.share ? randomBytes(6).toString('base64url') : undefined; rooms.saveTemplate({ id, game: body.game, config: body.config, shareCode }); return reply.code(201).send({ id, game: body.game, config: body.config, shareCode }); });
  app.get('/api/templates/:id', async (request, reply) => { const row = rooms.getTemplate((request.params as { id: string }).id); if (!row) return reply.code(404).send({ error: '模板不存在' }); return { id: row.id, game: row.game, config: parse(row.config, {}), shareCode: row.share_code }; });
  app.delete('/api/templates/:id', async (request, reply) => { const id = (request.params as { id: string }).id; if (!rooms.deleteTemplate(id)) return reply.code(404).send({ error: '模板不存在' }); return reply.code(204).send(); });
  app.get('/*', async (_request, reply) => reply.type('text/html').send(page()));
}
